### PR TITLE
Kelly fraction calculator

### PR DESCRIPTION
**Pull request by gregoryross**
@kamran-haider To get us started, I've added a simple function to calculate the optimal Kelly fraction for a coin toss with uneven payoffs.

I thought we could use this pull request to discuss what attributes and functions we'd like for our python class. To initialize the class, we might only require the probability of winning and initial wealth, with the calculation of the optimal fraction, estimated log growth rate, expected return after a number of trials being functions. Another cool thing to have would be calculating the probability of reaching or exceeding a return after a given number of runs. Something like

```
game = KellyBetSimple(p = 0.6, initial_amount=100)
game.get_optimal_fraction()
print game.fraction        
game.return(ntrials=100)
game.prob_return(return = 100, ntrails= 10)
```

What do you think?

### CODE REVIEW

**Comment by kamran-haider** [comment]
@gregoryross 
Sounds great. I also starting putting together some test functions e.g., generating a sequence of coin tosses, with same probability as p in the above code. 
Not entirely sure if we will eventually use this but just in case. I think we can hack these together to do some quick tests as how the Xn grows over a given sequence of trials and using your kelly fraction calculator. I also like the above framework overall.

**Comment by optimus-primo** [comment]
@gregoryross 
I am also still trying to figure out the most optimal way of working collaboratively in Git/Github. On my fork, I added the script I wrote to the scratch directory you created. I liked the idea of putting rough code into scratch. I will create a pull request to make sure the main repo looks like that as well and then you can sync your fork (sorry if this sounds complicated). I am sure, we don't have to do this frequently, just trying these things out to learn how github works.

I also was looking at the best way to keep forks synced coz I wanted to use the function you wrote. So I followed the steps in this: https://help.github.com/articles/syncing-a-fork/  to make sure that I have the update repo, after I merged your pull request.

**Comment by gregoryross** [comment]
@kamran-haider I really like the idea of having of your coin tossing function to generate data that we can compare the analytical results with (i.e. mean wealth at time some time, variance e.t.c). Analytics and numerics should fit together very nicely in a single class.

As for standardising the way we commit and keep up to date with this repo, how about we always do a pull request when we want to push a commit from our fork to the main repo, and only merge when the other has seen it and replied? Thanks for the link on how to keep forks up to date with upstream repos. As you say, we can use that method to keep our own repositories up to date with the main repo. 

By the way, you've replied as `optimus-primo`! I don't think we need to log in as him (it?) because we both have push and merge privileges. If you want to sign in as 'optimus', but don't want to sign out of you're own GitHub account, I suggest using up a 'private browser' window, as that will contain no login information, circumventing any need to sign out from `kamran-haider`.

**Comment by kamran-haider** [comment]
@gregoryross yeah I noticed right away that I forgot to sign out. I agree that since we have push and merge privileges so no need to use that account unless needed for some other purpose. 
I am a bit lost on the merge part though, let's say if I generate a pull request and you have replied and ok'd it. Who should do the merge then? I mean can I merge my own pull request (not sure if I can do that)? or can either of us do that? Overall I like the workflow you suggested, it is simple and sufficient for our purpose.

**Comment by gregoryross** [comment]
Hmm... how about: once the other has agreed to a pull request, the person who opened the pull merges it? (I think it's possible to merge one's own pull request.) That way, it's easy to keep track of who's done what, as GitHub recognizes the person who 'merges' as the person who commits.

**Comment by kamran-haider** [comment]
ok, that sounds good. Thanks

**Pull request merged**
