### PR TITLE
Added notebook with some initial demos

### PR DESCRIPTION
**Pull request by kamran-haider**
@gregoryross I started some very basic demos into the notebook. Will add some more stuff tomorrow. I will probably ping you tomorrow morning to talk about a few things.

### CODE REVIEW

**Comment by gregoryross** [comment]
Hey @kamran-haider, looks really good so far! I like the descriptions in the Markdown.

It looks like you've made a minor typo. In the first code block, you have 

```
coin = SingleCoinBetting(p=0.55, initial_logwealth=capital)
growth_expected = []
for i in xrange(m):
    growth.append(coin.predict_gamble(n, None))
```

where I think you mean to have 

```
for i in xrange(m):
    growth_expected.append(coin.predict_gamble(n, None))
```

so the `growth` and `growth_expected` have different entries. With this pull request, you can make the correction and commit to your repo and the pull request will be automatically updated. Afterwards, please merge at your leisure!

I have a suggestion too, but please feel free to keep things as they are if you want. You only need to initialize the `SingleCoin` class once, and call `predict_gamble()` and `gamble()` in the same loop, so long as `predict_gamble()` is called first. i.e.

```
coin = SingleCoinBetting(p=0.55, initial_logwealth=capital)
growth = []
growth_expected = []
for i in xrange(m):
    growth_expected.append(coin.predict_gamble(n))
    growth.append(coin.gamble(n))
```

You can do this because `coin.predict_gamble(n)` doesn't modify `coin.logwealth` whereas `coin.gamble(n)` does.

**Comment by gregoryross** [comment]
Oh yeah, and please feel free to ping me, although I may only be able to respond in the afternoon.

**Comment by kamran-haider** [comment]
@gregoryross  Thanks for the pointers. I was under the impression that both `gamble` and `predict_gamble` update `logwealth`. Thanks for pointing out the typo as well.

I am starting to look at the `probability_reaching_target` function. You have added a comment, saying it can output probabilities greater than 1. Does that mean there is a problem in the code? I do see strange numbers when I test this function.

**Comment by gregoryross** [comment]
@kamran-haider My pleasure!

I had a go at adding the dependency on the initial wealth (`logwealth`) for both `probability_reaching_target` and `probability_exceeding_target` where I defined `beta`. What I wrote is almost certainly incorrect except for the case when `logwealth=0`! We need to think about what the correct way to treat `logwealth` is for these functions.

**Comment by kamran-haider** [comment]
@gregoryross 
No worries, my initial code was also quite rigid and only worked for the book example. 
First thing to clarify is that, going by book notation, is `C` an actual target capital or a target factor by which we want wealth to increase on or before `n` trials?

**Comment by gregoryross** [comment]
From what I understand, `C` is the actual target capital.

**Comment by kamran-haider** [comment]
I see. So the main term where we need to account for `logwealth` is `beta` right? 
The numerator `beta` is currently defined as `np.log(target) - self.logwealth` which I think can be interpreted as a log ration of growth. Changing this to `logC` as in the book doesn't fix the problem either.

**Comment by gregoryross** [comment]
The numerator in `beta` was my naive guess, but we have to be missing something given that the probabilities are not correct. I'm going to have sit down properly and go through the derivation, otherwise I really don't know.

**Comment by kamran-haider** [comment]
@gregoryross 
Surprisingly, reverting  back to `lnC` produces a somewhat well-behaved probability function (as a function of number of trials). Here I am plotting probability of doubling wealth as a function of n trials:
image

So I will stop at this point, since I am moving office tomorrow. Feel free to modify the notebook. I will have some time on Saturday afternoon in case you want to talk.

**Comment by kamran-haider** [comment]
Also, let me know if this would be a good point to merge PR.

**Comment by gregoryross** [comment]
@kamran-haider Okay, that plot makes sense, nice test. Whatever I wrote was totally off I think. Please feel free to merge.

**Pull request merged**
